### ISSUE TITLE
Python interface for Swedish tagger does not work

### ISSUE THREAD

**Issue by munterkalmsteiner** [robertostling/efselab#18]
I've build the swedish pipeline and it is working fine with swe_pipeline.py.
Now I'd like to use the python interface, but I get the following error:

Python 3.6.5 (default, Apr 12 2018, 22:45:43) 
[GCC 7.3.1 20180312] on linux
Type "help", "copyright", "credits" or "license" for more information.
$ import udt_suc_sv
$ with open('swe-pipeline/suc.bin', 'rb') as f: weights = f.read()
... 
$ udt_suc_sv.tag(weights, ['öppningsbar', 'bro', '.'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Expected 3 fields for token, found single string 
$

What am I doing wrong?

**Comment by robertostling** [comment]
The `udt_suc_sv` model is used internally to translate between the SUC and Universal Dependencies tagsets. You probably want to use the `suc` model:

```
>>> import suc
>>> with open('swe-pipeline/suc.bin', 'rb') as f: weights = f.read()
... 
>>> suc.tag(weights, ['öppningsbar', 'bro', '.'])
('JJ|POS|UTR|SIN|IND|NOM', 'NN|UTR|SIN|IND|NOM', 'MAD')
```

If you want UD output, I recommend basing your code on `swe_pipeline.py` since the process is rather complex with separate models for tagging, lemmatization, and tagset translation.

**Comment by munterkalmsteiner** [comment]
Ok, I see. I'll then get a license for the SUC corpus. Thanks!

**Comment by robertostling** [comment]
I don't think you need the SUC corpus, if you are just interested in tagging. All you need should be included in the Swedish pipeline model package.

**Comment by munterkalmsteiner** [comment]
Wow, thanks! Yes, I misunderstood what was included in the pipeline.
