### ISSUE TITLE
Trouble with Swedish pipeline

### ISSUE THREAD

**Issue by nbloms** [robertostling/efselab#7]
Hi,
I'm trying to create a tagger with the swedish pipeline on a machine running win10 and Cygwin. 
When I run the command 'python3 build_suc.py --skip-generate --python --n-train-fields 2' I get some gcc output and then nothing happens, have been waiting for 30+ minutes. 
I've taken a printscreen that shows the efselab folder as well as my terminal here: http://imgur.com/ApdwxQI

Any idea of what's missing/wrong or how to debug this?

**Comment by robertostling** [comment]
I guess there is something with the compiler setup that doesn't like the very large C files produced by efselab. It takes some time to compile on any system, but more than a minute sounds bad.

Perhaps you could try to disable some optimizations? Add the option `--cflags '\-O0'` to build_suc.py (note that I just pushed a fix to make escaped dashes in --cflags work), but it probably won't do much difference.

**Comment by nbloms** [comment]
Hi, thanks for the quick answer.
When running only `python3 build_suc.py --cflags O0` i get the following error in tools.py line 9: `FileNotFoundError: [Errno 2] No such file or directory: 'suc-data/suc-blogs.tab` 

If i run `python3 build_suc.py --skip-generate --python --n-train-fields 2 --cflags O0` I get  `gcc error: O0:No such file or directory`

**Comment by robertostling** [comment]
Sorry that this time my answer was not as quick, but you forgot the (escaped) dash before O0. And yes, you need to use the other command line options as well (as in your second example).

**Comment by nbloms** [comment]
Hi, worry for late answer on my part as well. I get the same error even if i insert an escaped dash.
`gcc: error: \-O0: No such file or directory`

**Comment by robertostling** [comment]
It works for me, this is the complete command that I use for testing:
`python3 build_suc.py --skip-generate --python --n-train-fields 2 --cflags '\-O0'`

**Comment by nbloms** [comment]
Hi, sorry for the late reply. I got it working on a machine running Linux Mint and it's working great so far. 

The issue I'm facing now is when trying to implement this in an application. I'm trying to develop an application that helps a user to anonymize texts by pointing out potentially important words or phrases. I was thinking of using NER for this and highlight words in the text that is labelled as persons for example. 

When using NER in the swedish pipeline from command line i need to use taggning and lemmatizations as well and in doing so I get the output files of this. I don't really need this seeing as the only thing that's relevant is the NER tags. Is there a way to use the Swedish pipeline so that I only get the NER tags as output or should I tackle the issue in another way? I've seen in the description that I can use the different taggers as python modules, what functions are available in these modules except for the tag function demonstrated in the instructions?
