### ISSUE TITLE
Minor error in suc-saldo.lemmas

### ISSUE THREAD

**Issue by EmilStenstrom** [robertostling/efselab#9]
In the suc-saldo.lemmas file there's a minor error:

All words that start with "alkoholinnehav" have a zero width space in front of them which makes it not match any lemmatization rules. I found it by simply sorting the file and seeing that "alkoholinnehav" ended up at the bottom of the list instead with with other A-words.

**Comment by EmilStenstrom** [comment]
Actually, it seems it doesn't affect which lemmatization rule it matches since you select from the end of the word. Seems like a good idea to remove the space anyway though.

**Comment by robertostling** [comment]
This was a problem in the version of the SALDO lexicon I used, thanks for pointing it out. The model package has been updated.
